### ISSUE TITLE
Preact support

### ISSUE THREAD

**Issue by crazy4groovy** [Adrinlol/create-react-app-adrinlol#2]
Hello, love the concept, thanks for sharing.

It seems like the React lib/bundle might be rather overweight for the intended purpose; is their any consideration for supporting Preact in the future?

Cheers!

**Comment by Adrinlol** [comment]
Hi, thank you for the feedback.

You are absolutely correct about the bundle being overweight for a landing page. 

I plan on expanding this template, adding new sections/pages (pricing, payment with stripe, leaflet, about us, etc..) for the future, that is why just I'll stick to React for this project.
